### ISSUE TITLE
Not working for TWW?

### ISSUE THREAD

**Issue by letticee** [TimothyLuke/Cursor-Cooldown#13]
Already loaded the addone but didn't see it in option page and can't open the setting via /cc.

**Comment by TimothyLuke** [comment]
My focus has been on https://github.com/TimothyLuke/GSE-Advanced-Macro-Compiler and havnt looked at this yet to be honest

**Comment by letticee** [comment]
The Flavors should be "Retail" on curseforge, so it can be installed from curseforge app :P
![image](https://github.com/user-attachments/assets/d27657dc-4765-49da-a241-27a20290a267)

**Comment by TimothyLuke** [comment]
Thats curseforge's packager failing

**Comment by letticee** [comment]
Ah, I see. Thank you!<3

**Comment by TimothyLuke** [comment]
It should be showing for Retail now though
